apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp

spec:
  replicas: 1
  selector:
    matchLabels:
      name: simple-webapp
  template:
    metadata:
      labels:
        name: simple-webapp
        env: dev
    spec:
      containers:
      - env:
        - name: APP_START_DELAY
          value: "10"
        image: webapp-delayed-start:latest
        imagePullPolicy: Never
        name: simple-webapp
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
            httpGet:
              path: /live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 2
            failureThreshold: 3
  
